### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by samdemaeyer** [paosch/memory-game#1]
**Task:**
On a new branch:
- [ ] Create a grid that displays 16 cards, a grid 4 by 4.
- [ ] Make sure the cards are all squares **200px** by **200px**
  - [ ] Add and include a new CSS file.
  - [ ] The file cannot include more than 4 lines of CSS
- [ ] Remove the `<h1>` title
- [ ] Add margin on the top and bottom of the container div with a single class with the size `5`
- [ ] Replace `margin-bottom` of each card with the size `5`
- [ ] Wrap the number in `<h4>` and make it white and make sure it's centered in the middle of the card using bootstrap utilities.

**End result:**
<img width="1038" alt="Screenshot 2019-08-10 at 16 43 56" src="https://user-images.githubusercontent.com/7160913/62823865-2579cc00-bb8e-11e9-99b1-566d26229778.png">

@paosch @ChrisBaidoo
